image: maven:latest

stages:
  - build
  - test
#  - run

variables:
#  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - cd engine/
    - mvn $MAVEN_CLI_OPTS compile
#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test

package:
  stage: test
  script:
    - cd engine/
    - mvn $MAVEN_CLI_OPTS package

#run:
#  stage: run
#  script:
#    - mvn $MAVEN_CLI_OPTS package
#    - mvn $MAVEN_CLI_OPTS exec:java -Dexec.mainClass="com.example.app.App"
