####
#
## To Build Docker Image
# $> mvn clean package -Dmaven.test.skip=true -Dquarkus.package.type=uber-jar 
# $> docker build -f src/main/docker/Dockerfile.jvm -t kyc-engine .
#
## To Execute Container
# $> docker run -i -t --rm -p 8080:8080 kyc-engine
###
FROM openjdk:17

ENV RUNTIME_TYPE quarkus
RUN mkdir /app
COPY target/*.jar /app

CMD java -jar /app/kyc-dmn-runner.jar